### ISSUE TITLE
Robot does not move "Baud rate issue"

### ISSUE THREAD

**Issue by kristjanp28** [UbiquityRobotics/ubiquity_motor#83] opened 2020-05-12 18:46 UTC
Problem: Robot dosen't move with teleop.
Procedure for reproduction the error:

MCB: 5.2 known working board.
Image: 2020-02-10-ubiquity-xenial-lxde-raspberry-pi.img
Firmware: v35

procedure:
- Power up
- wait for SIN and SOUT to blink / 3 minutes to boot up
- move robot around with teleop
- shutdown with 'sudo shutdown -h now'
- power off with switch

observations:
- motor_node uses ~60% of cpu
- `sudo stty -F /dev/ttyAMA0` return baud rate of 38400
- rosout.log returns bunch of 'REJECT' messages
- killing motor_node and restarting it with `rosrun ubiquity_motor motor_node` returns exact 'REJECT' messages as log file.
- setting baud rate to 38400 with `sudo stty -F /dev/ttyAMA0 38400` and starting the motor_node returns no errors.

**Comment by rohbotics** [comment] 2020-07-09 05:53
@mjstn @kristjanp28 Have we gotten this bug again?

**Comment by mjstn** [comment] 2020-08-15 01:13
This defect is a duplicate of https://github.com/UbiquityRobotics/ubiquity_motor/issues/95
Closing this now as it is the same defect.

**Closed as completed by mjstn** 2020-08-15 01:13 UTC
