### ISSUE TITLE
Make sure that the MCB knows the version through power cycle

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_motor#63] opened 2019-04-17 16:34 UTC
If we power down the controller board but not ROS then power up controller board the board will not know its version

**Comment by mjstn** [comment] 2021-04-13 06:04
As of version 5.2 MCB board which has been our main shipping version followed now by rev 5.3  a resistor divider allows us to determine MCB version is 5.2,5.3  or some earlier version.  That is sufficient to satisfy this issue.  
the issue is being closed as being addressed well enough at this time.

**Closed as completed by mjstn** 2021-04-13 06:04 UTC
